# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c408e2a40516983df8759a4b0b496ed4a09ed2c51b35c28dc4ba614dc3e5c5d57014223bfa1b237604cbfc5c7f37a11b134145b210ac6d7f38f6ae7d737d4dc1
  sendpulse_api_key: <%= ENV["SENDPULSE_API"] %>
  sendpulse_api_secret: <%= ENV["SENDPULSE_SECRET"] %>

test:
  secret_key_base: 1ed83bb029755348d7aafee8881bbd91ad03b1f050cc178e14fd80d684c8f08d9db3bfba8c2f3d4e8734c7b1bfaa40ed7ed288977685ec8751aa6b3f8534dc5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendpulse_api_key: <%= ENV["SENDPULSE_API"] %>
  sendpulse_api_secret: <%= ENV["SENDPULSE_SECRET"] %>
